# Generated by Django 3.2.16 on 2023-07-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='str_id',
            field=models.TextField(default='<django.db.models.fields.UUIDField>'),
        ),
    ]
