# Generated by Django 3.2.16 on 2023-07-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_str_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='str_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.TextField(default='42c2a234-6451-4537-9016-ffba203ece40', primary_key=True, serialize=False),
        ),
    ]
