# Generated by Django 3.2.16 on 2023-07-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230712_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.TextField(default='d148e632-f819-42dd-bd88-ad73c5d91252', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.TextField(default='8ec745a2-b459-4c42-9513-5f5ceb8a6871', primary_key=True, serialize=False),
        ),
    ]
