# Generated by Django 3.2.16 on 2023-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230712_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.TextField(default='45c33a0b-c0cd-4b3d-91e9-a48f80bc1912', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='f',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.TextField(default='36dd7baa-33db-419b-981f-47e711da99e0', primary_key=True, serialize=False),
        ),
    ]
