# Generated by Django 3.2.16 on 2023-07-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230712_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='f',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.TextField(default='6e4b55b7-914b-4a52-9a61-882a0f300f39', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.TextField(default='0fd64513-5a54-4f15-9271-6c2980369d22', primary_key=True, serialize=False),
        ),
    ]
