# Generated by Django 3.2.16 on 2023-07-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230712_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.TextField(default='2a297c6d-c7ba-479e-a024-e07c0054c68d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.TextField(default='1697a099-6bb4-4877-9c5c-fabd5b8cab26', primary_key=True, serialize=False),
        ),
    ]
