# Generated by Django 3.2.16 on 2023-07-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230712_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
